language: node_js
notifications:
  email: false
node_js:
  - 'node'
  - '6'
  - '4'
before_script: ./node_modules/.bin/remove-lockfiles
after_success:
  - npm install -g codecov
  - codecov
branches:
  only:
    - master
    - /^greenkeeper/.*$/
